### PR TITLE
Interactive editing of env settings.

### PR DESCRIPTION
**Pull request by lazyatom**
Given that we can't 'unset' easily, perhaps this is a useful way of manipulating env settings.

### CODE REVIEW

**Comment by tomafro** [comment]
This looks a promising approach.  I like it.  There may be an issue with the permissions of the uploaded file though.  I''ll try and test it tomorrow and give it a whirl.

**Comment by tomafro** [comment]
I did find a problem with the permissions of the uploaded file, and also with the use of EDITOR (at least if EDITOR is set to `mate` rather than `mate -w`), so I've taken the general approach and implemented it in 1dd237422 rather than this pull request.  Hope that's ok.

**Comment by lazyatom** [comment]
Yep - that's cool. Out of interest - how does the approach in 1dd2374 avoid whatever the permissions problem was?

**Comment by tomafro** [comment]
It doesn't, because I'm a dick and forgot to add the line that fixes it.

**Comment by tomafro** [comment]
Fixed (hopefully) here: 0a60f1977dc

**Pull request closed without merging**
