### PR TITLE
Configure foreman concurrency

### PR DESCRIPTION
**Pull request by hakanensari**
Recap helped me radically clean up some recipes. Thanks, guys.

This PR exposes the foreman concurrency variable.

### CODE REVIEW

**Comment by lazyatom** [comment]
Looks good to me.

**Comment by tomafro** [comment]
I definitely think you should be able to define foreman concurrency, but I'm hoping I can come up with a slightly more flexible solution.  I'd like to be able to define concurrency on a server by server basis, as in this contrived example:

```
server 'huge.example.com', :app, processes: {web: 10, queue: 10}
server 'small.example.com', :app, processes: {web: 1}
```

Perhaps this pull request is a useful stop-gap solution and the more flexible solution can be part of version 2.0.  Let me think about it for a little while.

**Comment by tomafro** [comment]
@hakanensari I forgot to say thank you very much for the pull request - whether it gets accepted or not it is very much appreciated.

**Comment by hakanensari** [comment]
@tomafro, I like your per-server declaration idea so went ahead and implemented it.

Caveat: This runs exports server by server serially but my small apps can live with that.

Have a look at Capistrano's janky [parallel](https://github.com/capistrano/capistrano/wiki/2.x-DSL-Action-Invocation-Parallel) command, though. Perhaps there's a way to parallelise this using that, which would help if you have a lot of server definitions.

**Comment by tomafro** [comment]
This looks really interesting hakan.  I've been doing a bit of clean up work but once done I'll look to merge it in.  Thanks!

**Pull request closed without merging**
